version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 10
    commands:
      - npm install

  build:
    commands:
      - echo Starting build
      - npm run build
      - echo Build successful
  post_build:
    commands:
      - echo "$PWD"
    artifacts:
      files:
        - ../public/**/*
