version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 10
    build:
      commands:
        - echo Starting build
        - npm run build
        - echo Build successful
    post_build:
      artifacts:
        files: ./public/**/*
